# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: 'bnb.scaffoldtranslation::lang.demo.label'

# Model Form Field configuration
form: $/bnb/scaffoldtranslation/models/demo/fields.yaml

# Model Class name
modelClass: BnB\ScaffoldTranslation\Models\Demo

# Default redirect location
defaultRedirect: bnb/scaffoldtranslation/demo

# Create page
create:
    title: 'bnb.scaffoldtranslation::lang.demo.create_title'
    redirect: bnb/scaffoldtranslation/demo/update/:id
    redirectClose: bnb/scaffoldtranslation/demo

# Update page
update:
    title: 'bnb.scaffoldtranslation::lang.demo.update_title'
    redirect: bnb/scaffoldtranslation/demo
    redirectClose: bnb/scaffoldtranslation/demo

# Preview page
preview:
    title: 'bnb.scaffoldtranslation::lang.demo.preview_title'